language: node_js
node_js:
  - "7"
before_script:
  - npm install -g typings
  - npm install -g typescript
  - typings install
  - tsc
  - mkdir ./dist/spec
services:
  - couchdb
script:
  - npm test
notifications:
    slack: teyssedre:FWPzqLce2Lt9AoHPiaMZsrhP